export const CURRENCIES = [
  { code: "AED", name: "United Arab Emirates Dirham", locale: "ar-AE" },
  { code: "ARS", name: "Argentine Peso", locale: "es-AR" },
  { code: "AUD", name: "Australian Dollar", locale: "en-AU" },
  { code: "BDT", name: "Bangladeshi Taka", locale: "bn-BD" },
  { code: "BGN", name: "Bulgarian Lev", locale: "bg-BG" },
  { code: "BHD", name: "Bahraini Dinar", locale: "ar-BH" },
  { code: "BND", name: "Brunei Dollar", locale: "ms-BN" },
  { code: "BOB", name: "Bolivian Boliviano", locale: "es-BO" },
  { code: "BRL", name: "Brazilian Real", locale: "pt-BR" },
  { code: "CAD", name: "Canadian Dollar", locale: "en-CA" },
  { code: "CHF", name: "Swiss Franc", locale: "de-CH" },
  { code: "CLP", name: "Chilean Peso", locale: "es-CL" },
  { code: "CNY", name: "Chinese Yuan", locale: "zh-CN" },
  { code: "COP", name: "Colombian Peso", locale: "es-CO" },
  { code: "CRC", name: "Costa Rican Colón", locale: "es-CR" },
  { code: "CZK", name: "Czech Koruna", locale: "cs-CZ" },
  { code: "DKK", name: "Danish Krone", locale: "da-DK" },
  { code: "DZD", name: "Algerian Dinar", locale: "ar-DZ" },
  { code: "EGP", name: "Egyptian Pound", locale: "ar-EG" },
  { code: "EUR", name: "Euro", locale: "de-DE" },
  { code: "GBP", name: "British Pound", locale: "en-GB" },
  { code: "GHS", name: "Ghanaian Cedi", locale: "en-GH" },
  { code: "HKD", name: "Hong Kong Dollar", locale: "zh-HK" },
  { code: "HRK", name: "Croatian Kuna", locale: "hr-HR" },
  { code: "HUF", name: "Hungarian Forint", locale: "hu-HU" },
  { code: "IDR", name: "Indonesian Rupiah", locale: "id-ID" },
  { code: "INR", name: "Indian Rupee", locale: "hi-IN" },
  { code: "IQD", name: "Iraqi Dinar", locale: "ar-IQ" },
  { code: "IRR", name: "Iranian Rial", locale: "fa-IR" },
  { code: "ISK", name: "Icelandic Króna", locale: "is-IS" },
  { code: "JMD", name: "Jamaican Dollar", locale: "en-JM" },
  { code: "JOD", name: "Jordanian Dinar", locale: "ar-JO" },
  { code: "JPY", name: "Japanese Yen", locale: "ja-JP" },
  { code: "KES", name: "Kenyan Shilling", locale: "en-KE" },
  { code: "KRW", name: "South Korean Won", locale: "ko-KR" },
  { code: "KWD", name: "Kuwaiti Dinar", locale: "ar-KW" },
  { code: "KZT", name: "Kazakhstani Tenge", locale: "kk-KZ" },
  { code: "LBP", name: "Lebanese Pound", locale: "ar-LB" },
  { code: "LKR", name: "Sri Lankan Rupee", locale: "si-LK" },
  { code: "MAD", name: "Moroccan Dirham", locale: "ar-MA" },
  { code: "MMK", name: "Myanmar Kyat", locale: "my-MM" },
  { code: "MXN", name: "Mexican Peso", locale: "es-MX" },
  { code: "MYR", name: "Malaysian Ringgit", locale: "ms-MY" },
  { code: "NGN", name: "Nigerian Naira", locale: "en-NG" },
  { code: "NOK", name: "Norwegian Krone", locale: "nb-NO" },
  { code: "NZD", name: "New Zealand Dollar", locale: "en-NZ" },
  { code: "OMR", name: "Omani Rial", locale: "ar-OM" },
  { code: "PEN", name: "Peruvian Sol", locale: "es-PE" },
  { code: "PHP", name: "Philippine Peso", locale: "en-PH" },
  { code: "PKR", name: "Pakistani Rupee", locale: "ur-PK" },
  { code: "PLN", name: "Polish Zloty", locale: "pl-PL" },
  { code: "QAR", name: "Qatari Riyal", locale: "ar-QA" },
  { code: "RON", name: "Romanian Leu", locale: "ro-RO" },
  { code: "RSD", name: "Serbian Dinar", locale: "sr-RS" },
  { code: "RUB", name: "Russian Ruble", locale: "ru-RU" },
  { code: "SAR", name: "Saudi Riyal", locale: "ar-SA" },
  { code: "SEK", name: "Swedish Krona", locale: "sv-SE" },
  { code: "SGD", name: "Singapore Dollar", locale: "en-SG" },
  { code: "THB", name: "Thai Baht", locale: "th-TH" },
  { code: "TRY", name: "Turkish Lira", locale: "tr-TR" },
  { code: "TWD", name: "New Taiwan Dollar", locale: "zh-TW" },
  { code: "TZS", name: "Tanzanian Shilling", locale: "sw-TZ" },
  { code: "UAH", name: "Ukrainian Hryvnia", locale: "uk-UA" },
  { code: "USD", name: "United States Dollar", locale: "en-US" },
  { code: "UYU", name: "Uruguayan Peso", locale: "es-UY" },
  { code: "VND", name: "Vietnamese Dong", locale: "vi-VN" },
  { code: "XOF", name: "West African CFA Franc", locale: "fr-SN" },
  { code: "XAF", name: "Central African CFA Franc", locale: "fr-CM" },
  { code: "ZAR", name: "South African Rand", locale: "en-ZA" },
];
